apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-02-20T12:00:00Z"
  labels:
    app: flaskdemo
  name: flaskdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: "2023-02-20T12:00:00Z"
      labels:
        app: flaskdemo
    spec:
      containers:
      - image: rhodinnagwere/gitops:7
        name: flaskdemo
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flaskdemo
